data_ingestion:
  bucket_name: "hotel-reserve5824"
  bucket_file_name: "Hotel_Reservations.csv"
  train_ratio: 0.8


data_processing:
  categorical_columns:
    - "type_of_meal_plan"
    - "booking_status"
    - "room_type_reserved"
    - "market_segment_type"
    - "repeated_guest"
    - "required_car_parking_space"
  numerical_columns:
    - "lead_time"
    - "no_of_adults"
    - "no_of_children"
    - "no_of_weekend_nights"
    - "no_of_week_nights"
    - "avg_price_per_room"
    - "no_of_special_requests"
    - "arrival_year"
    - "arrival_month"
    - "arrival_date"
    - "no_of_previous_bookings_not_canceled"
    - "no_of_previous_cancellations"
  skewness_threshold: 5
  no_of_features: 10